### ISSUE TITLE
StriderMqtt.MqttProtocolException: Could not read remaining length

### ISSUE THREAD

**Issue by carmanlwf** [ericvoid/StriderMqtt#7]
在 StriderMqtt.PacketReader.ReadRemainingLength(Stream stream)
   在 StriderMqtt.PacketReader..ctor(Stream stream)
   在 StriderMqtt.MqttConnection.ReadPacket()
   在 StriderMqtt.MqttConnection.ReceivePacket()
   在 StriderMqtt.MqttConnection.Loop(Int32 readLimit)
   在 StriderMqtt.MqttConnection.Loop()
   在 EmptyPublishing.MqttClient.Run()

**Comment by ericvoid** [comment]
What broker are you connecting to?

Do you know what packet the client is trying to read?

**Comment by carmanlwf** [comment]
1. broker is rabbitmq
2. I do not know the specific data packets, through the log file to understand this exception

sometimes Exception

Exception： StriderMqtt.MqttTimeoutException: 引发类型为“StriderMqtt.MqttTimeoutException”的异常。
在 StriderMqtt.MqttConnection.Loop(Int32 readLimit)
在 StriderMqtt.MqttConnection.Loop()
在 EmptyPublishing.MqttClient.Run()引发类型为“StriderMqtt.MqttTimeoutException”的异常

At 2017-12-20 00:41:00, "ericvoid" <notifications@github.com> wrote:


What broker are you connecting to?

Do you know what packet the client is trying to read?

**Comment by ericvoid** [comment]
`MqttTimeoutException` is normal to be thrown. It just means that the connection is not valid anymore due to timeout. In this case, catch the exception and connect again.

I just pushed a changeset adding some details on `MqttProtocolException`s. Please checkout to the last change.
